### ISSUE TITLE
Italian translation of documentation

### ISSUE THREAD

**Issue by cerelli** [orocrm/documentation#233]
Hi, i want to translate this documentation in italian language. How ?
Thanks.

**Comment by mbessolov** [comment]
Hi @cerelli ,

Just create a new branch and start translating. We would be happy to publish it on the website once at least some articles are translated completely.

PS. If you did not do it yet, please start with signing the Contributor License Agreement at http://www.orocrm.com/contributor-license-agreement , so that your translation can be accepted.

Thank you,
Michael

**Comment by cerelli** [comment]
Excuse me, how can i create a new branch ?
Thanks.

**Comment by mbessolov** [comment]
* I see you've already forked the documentation repository. 
* The next step would be to creating a branch in your fork, just follow the GitHub guide at https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/#creating-a-branch
* And step 3, after you are done translating some articles - create a pull request https://help.github.com/articles/creating-a-pull-request-from-a-fork/ (you can target the master branch of our repository as a base when creating it, we will take care of branch logistics on our side).

**Comment by mkudelya** [comment]
Hi @cerelli 

I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
